### PR TITLE
Keep BC in ChainOptimizer

### PR DESCRIPTION
**Pull request by umpirsky**
As described in https://github.com/psliwa/image-optimizer/pull/47.

### CODE REVIEW

**Comment by umpirsky** [comment]
@psliwa Can you please take a look?

**Comment by umpirsky** [comment]
@psliwa Ping.

**Comment by umpirsky** [comment]
@psliwa Pong.

**Comment by psliwa** [comment]
My reasoning about not accepting this PR is here: https://github.com/psliwa/image-optimizer/pull/47#issuecomment-363890458. It would introduce BC-break once again when I release it as 1.1.x or even as 1.2.x. Releasing this as 2.x.x won't improve anything, because cleaner constructor signature is IMHO without default parameters. In the future I will be more strict about BC-breaks and semantic versioning, even if I didn't commit to semantic versioning before (my idea was to have `minior.patch.bug-fix` approach, but probably it is less intuitive for the users).

**Comment by umpirsky** [comment]
OK, thanks. But I still think this BC break was unnecessary. :)

**Pull request closed without merging**
